#!/usr/bin/python3
'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
'''

from time import time


def main():
    a = 0
    b = 1
    c = 0

    total_of_evens = 0
    while c < 4_000_000:
        if c % 2 == 0:
            total_of_evens += c

        c = a + b
        a = b
        b = c

    print(f'Sum of even-valued terms < 4,000,000: {total_of_evens}')


if __name__ == '__main__':
    start = time()
    main()
    print(f'Time: {time() - start}s')
